[keymap]
preset = "default"

[keymap.overrides]

[completion]
activate_on_typing = true
copilot = false

[display]
default_width = "medium"
dataframes = "rich"
theme = "system"
cell_output = "below"
code_editor_font_size = 12

[server]
browser = "default"
follow_symlink = false

[experimental]

[package_management]
manager = "uv"

[save]
autosave = "after_delay"
format_on_save = true
autosave_delay = 1000

[runtime]
auto_reload = "autorun"
auto_instantiate = true
on_cell_change = "autorun"

[ai.open_ai]

[formatting]
line_length = 79
