[server]
follow_symlink = false
browser = "default"

[keymap]
preset = "default"

[keymap.overrides]

[experimental]

[runtime]
auto_instantiate = true
on_cell_change = "autorun"
auto_reload = "autorun"

[save]
format_on_save = true
autosave = "after_delay"
autosave_delay = 1000

[completion]
activate_on_typing = true
copilot = false

[display]
cell_output = "below"
code_editor_font_size = 12
theme = "system"
dataframes = "rich"
default_width = "medium"

[package_management]
manager = "uv"

[ai]
rules = ""

[ai.open_ai]

[formatting]
line_length = 79
