return {
	{ src = "https://github.com/neovim/nvim-lspconfig", name = "nvim-lspconfig" },
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", name = "nvim-treesitter", version = "main" },
	{
		src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects",
		name = "nvim-treesitter-textobjects",
	},
	{ src = "https://github.com/windwp/nvim-ts-autotag", name = "nvim-ts-autotag" },
	{
		src = "https://github.com/Saghen/blink.cmp",
		name = "blink.cmp",
		version = vim.version.range("1"),
	},
	{ src = "https://github.com/L3MON4D3/LuaSnip", name = "LuaSnip" },
	{ src = "https://github.com/windwp/nvim-autopairs", name = "nvim-autopairs" },
	{ src = "https://github.com/numToStr/Comment.nvim", name = "Comment.nvim" },
	{ src = "https://github.com/echasnovski/mini.nvim", name = "mini.nvim" },
	{ src = "https://github.com/folke/flash.nvim", name = "flash.nvim" },
	{ src = "https://github.com/folke/which-key.nvim", name = "which-key.nvim" },
	{ src = "https://github.com/stevearc/oil.nvim", name = "oil.nvim" },
	{ src = "https://github.com/mg979/vim-visual-multi", name = "vim-visual-multi" },
	{ src = "https://github.com/folke/snacks.nvim", name = "snacks.nvim" },
	{ src = "https://github.com/nvim-tree/nvim-web-devicons", name = "nvim-web-devicons" },
	{ src = "https://github.com/akinsho/bufferline.nvim", name = "bufferline.nvim" },
	{ src = "https://github.com/nvim-lualine/lualine.nvim", name = "lualine.nvim" },
	{
		src = "https://github.com/christoomey/vim-tmux-navigator",
		name = "vim-tmux-navigator",
	},
	{ src = "https://github.com/mfussenegger/nvim-lint", name = "nvim-lint" },
	{ src = "https://github.com/stevearc/conform.nvim", name = "conform.nvim" },
	{ src = "https://github.com/lewis6991/async.nvim", name = "async.nvim" },
	{ src = "https://github.com/algmyr/vclib.nvim", name = "vclib.nvim" },
	{ src = "https://github.com/algmyr/vcsigns.nvim", name = "vcsigns.nvim" },
	{ src = "https://github.com/Saecki/crates.nvim", name = "crates.nvim" },
	{ src = "https://github.com/hat0uma/csvview.nvim", name = "csvview.nvim" },
	{ src = "https://github.com/tpope/vim-dadbod", name = "vim-dadbod" },
	{ src = "https://github.com/kristijanhusak/vim-dadbod-ui", name = "vim-dadbod-ui" },
	{
		src = "https://github.com/kristijanhusak/vim-dadbod-completion",
		name = "vim-dadbod-completion",
	},
	{ src = "https://github.com/catppuccin/nvim", name = "catppuccin" },
	{ src = "https://github.com/Verf/deepwhite.nvim", name = "deepwhite.nvim" },
	{ src = "https://github.com/sainnhe/everforest", name = "everforest" },
	{ src = "https://github.com/xero/miasma.nvim", name = "miasma.nvim" },
	{
		src = "https://github.com/KimNorgaard/vim-frign",
		name = "vim-frign",
		version = "3abc464a7f21151bfdd596089ddcab80be658eb3",
	},
	{
		src = "https://github.com/aonemd/quietlight.vim",
		name = "quietlight.vim",
		version = "61b00ed7c9678c2b23a5ceec8b895001f76af56b",
	},
	{ src = "https://github.com/dmtrKovalenko/fff", name = "fff" },
}
