[tools]
atuin = "latest"
aube = "latest"
"github:agavra/tuicr" = "latest"
"github:astral-sh/hawk" = "latest"
"github:bede/skope" = "latest"
"github:jnsahaj/lumen" = "latest"
node = "latest"
"npm:scriptc" = "latest"
nub = { version = "latest", allow_builds = ["@nubjs/nub"] }
opencode = "latest"
pixi = "latest"
pnpm = "latest"
release-plz = "latest"
superhtml = "latest"
uv = "latest"
vp = "latest"
